stages:
  - build
  - test

image: gcc

build-job:
  stage: build
  before_script:
    - apt update && apt -y install asciidoctor
  script:
    - make
  artifacts:
    path:
      - curliff

test-job:
  stage: test
  script:
    - ./tests.sh
