'\" t
.\"     Title: curliff
.\"    Author: Francisco Oliveto
.\" Generator: Asciidoctor 2.0.10
.\"      Date: 2022-06-18
.\"    Manual: Curliff Manual.
.\"    Source: Curliff 1.0
.\"  Language: English
.\"
.TH "CURLIFF" "1" "2022-06-18" "Curliff 1.0" "Curliff Manual."
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
.SH "NAME"
curliff \- a little tool for removing spurious carriage returns from a text file.
.SH "SYNOPSIS"
.sp
\fBcurliff\fP [OPTIONS] [file...]
.SH "DESCRIPTION"
.sp
A little tool for removing spurious carriage returns from a text file.
It converts the combination <CR><LF> (pronounced "curliff") at the end of
each text line to the single line feed character <LF>.
.sp
If called with no arguments, this tool will filter standard input. The result
of the operation is written to standard output.
.sp
This tool is useful for situations in which a text file must be moved
back and forth between Windows and Unix systems.
.SH "OPTIONS"
.sp
\fB\-r\fP
.RS 4
Reverses the operation, turning <LF> into <CR><LF>.
.RE
.SH "EXAMPLES"
.sp
The user might need the output to be presisted in a file, in that case a
simple redirection will do:
.sp
.if n .RS 4
.nf
curliff inputfile >outputfile
.fi
.if n .RE
.sp
To inverse the operation:
.sp
.if n .RS 4
.nf
curliff \-r outputfile
.fi
.if n .RE
.sp
This example shows how to strip CRs from a file only in lines
that match certain text pattern. The result will be redirected to a file.
.sp
.if n .RS 4
.nf
grep "^a" infile | ./curliff >file
.fi
.if n .RE
.SH "COPYING"
.sp
Copyright (c) 2020 Francisco Oliveto.
SPDX\-License\-Identifier: BSD\-2\-clause.
.SH "AUTHOR"
.sp
Francisco Oliveto